#!/usr/bin/env node
// SPDX-License-Identifier: FSL-1.1-MIT
/**
 * holt — HOSTS.md generator.
 *
 * HOSTS.md used to claim it "tracks holt's own manifest" while admitting, in the very next
 * sentence, that nothing actually enforced that — it was hand-synced, and it drifted at least
 * twice: Cursor's promotion to a docs-verified block hook never made it into the file, and the
 * Roo/Kilo split (two products, two config formats) showed up here as a single stale row. A page
 * whose entire point is "here is exactly what protection your agent gets" is the worst possible
 * place for that kind of silent rot, because a reader has no way to know it happened.
 *
 * So the table (and the cloud-caveat paragraph, which is the same prose as the `CLOUD_CAVEAT`
 * export) are generated from `src/integrate/hosts.mjs` — the `HOSTS` array and `strengthLabel()`
 * are the ONLY source of truth — and regenerated between explicit markers, the same shape
 * README.md already uses for its social-proof block (`HOLT:SOCIAL-PROOF:BEGIN/END`,
 * scripts/milestone.mjs). Hand-written prose outside the markers (what each strength grade means,
 * the Devin/Windsurf rename note, etc.) is left completely alone.
 *
 *   node scripts/generate-hosts.mjs           # regenerate HOSTS.md in place
 *   node scripts/generate-hosts.mjs --check   # exit 1 if HOSTS.md disagrees with the manifest (CI)
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { HOSTS, strengthLabel, CLOUD_CAVEAT } from '../src/integrate/hosts.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const HOSTS_MD_PATH = path.join(ROOT, 'HOSTS.md');

// Same marker shape as README's `<!-- HOLT:SOCIAL-PROOF:BEGIN ... END -->` block. Two independent
// pairs, because the table and the cloud caveat come from two different exports and either one
// could change without the other.
export const TABLE_BEGIN =
  '<!-- HOLT:HOSTS-TABLE:BEGIN — generated by `npm run hosts:generate` from the HOSTS array and '
  + 'strengthLabel() in src/integrate/hosts.mjs. Do not hand-edit between these markers; edit the '
  + 'manifest and regenerate. -->';
export const TABLE_END = '<!-- HOLT:HOSTS-TABLE:END -->';

export const CAVEAT_BEGIN =
  '<!-- HOLT:CLOUD-CAVEAT:BEGIN — generated from the CLOUD_CAVEAT export in src/integrate/hosts.mjs. '
  + 'Do not hand-edit between these markers. -->';
export const CAVEAT_END = '<!-- HOLT:CLOUD-CAVEAT:END -->';

/** The exact table HOSTS.md ships, computed from the manifest alone. */
export function renderHostsTable(hosts = HOSTS) {
  const header = '| Host | Environment | holt integration |\n|---|---|---|';
  const rows = hosts.map((h) => `| ${h.name} | ${h.env} | ${strengthLabel(h)} |`);
  return [header, ...rows].join('\n');
}

/**
 * Replace the text strictly between one BEGIN/END marker pair with `body`, leaving the markers
 * themselves in place. Throws — does not silently no-op — if a marker is missing, duplicated, or
 * out of order, because a generator that quietly skips a deleted anchor ships a stale file
 * forever and looks, from the outside, exactly like one that is working.
 */
export function replaceBetweenMarkers(text, begin, end, body) {
  const b = text.indexOf(begin);
  if (b === -1) throw new Error(`generate-hosts: begin marker not found: ${JSON.stringify(begin)}`);
  if (text.indexOf(begin, b + 1) !== -1) {
    throw new Error(`generate-hosts: begin marker appears more than once: ${JSON.stringify(begin)}`);
  }
  const afterBegin = b + begin.length;
  const e = text.indexOf(end, afterBegin);
  if (e === -1) throw new Error(`generate-hosts: end marker not found after its begin marker: ${JSON.stringify(end)}`);
  if (text.indexOf(end, e + 1) !== -1) {
    throw new Error(`generate-hosts: end marker appears more than once: ${JSON.stringify(end)}`);
  }
  return `${text.slice(0, afterBegin)}\n${body}\n${text.slice(e)}`;
}

/** Pure: given HOSTS.md's current text, return what it SHOULD be for the given manifest. */
export function regenerate(existingText, hosts = HOSTS) {
  let next = replaceBetweenMarkers(existingText, TABLE_BEGIN, TABLE_END, renderHostsTable(hosts));
  next = replaceBetweenMarkers(next, CAVEAT_BEGIN, CAVEAT_END, CLOUD_CAVEAT);
  return next;
}

async function main() {
  const check = process.argv.includes('--check');
  const existing = await fs.readFile(HOSTS_MD_PATH, 'utf8');
  const next = regenerate(existing, HOSTS);

  // Compared after CRLF->LF folding: the gate's claim is that the CONTENT matches the manifest,
  // and a Windows checkout with core.autocrlf=true hands this process the same content in a
  // different encoding. Failing on that reported the file as stale on windows-latest while the
  // repository was correct. (.gitattributes now pins eol=lf as well; this keeps existing clones
  // honest.) The regenerated file itself is still written byte-exact.
  const lf = (s) => s.replace(/\r\n/g, '\n');
  if (lf(next) === lf(existing)) {
    console.log(check ? 'HOSTS.md matches the manifest.' : 'HOSTS.md already matches the manifest — nothing to do.');
    return;
  }

  if (check) {
    console.error('HOSTS.md is STALE: it does not match src/integrate/hosts.mjs.');
    console.error('Run `npm run hosts:generate` and commit the result.');
    process.exitCode = 1;
    return;
  }

  await fs.writeFile(HOSTS_MD_PATH, next, 'utf8');
  console.log('HOSTS.md regenerated from src/integrate/hosts.mjs.');
}

// pathToFileURL, not a raw `file://${process.argv[1]}` template: on Windows, argv[1] carries
// backslashes and no scheme (C:\path\to\script.mjs), while import.meta.url is a proper file URL
// (file:///C:/path/to/script.mjs). The string comparison never matched, so `main()` never ran
// when the script was invoked directly on Windows — the generator silently did nothing.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e) => { console.error(e?.stack || e?.message || e); process.exit(2); });
}
